stages:
  - check-url

variables:
  url: "https://carlosmagnoti.com.br"

run_python_script:
  stage: check-url
  image: python:3.13.11-alpine3.23
  when: manual
  before_script:
    - python --version
    - pip install uv
    - uv sync
  script:
    - echo "Running Python script..."
    - uv run python main.py $url
