stages:
  - check-url

variables:
  url: "https://carlosmagnoti.com.br"

run_python_script:
  stage: check-url
  image: python:3.13.11-alpine3.23
  when: manual
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install requests || echo "Error to install requests"
  script:
    - echo "Running Python script..."
    - python check_url.py $url
