name: Check URL

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL a ser verificada'
        required: true
        default: 'https://carlosmagnoti.com.br'

jobs:
  check-url:
    name: Check URL
    runs-on: ubuntu-latest
    container: python:3.13.11-alpine3.23
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Python version
        run: python --version

      - name: Install UV
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      - name: Run check script
        run: uv run python main.py ${{ github.event.inputs.url }}
